apiVersion: v1
kind: Secret
metadata:
  name: user-postgres-secrets
type: Opaque
data:
  username: dXNlcl91c2Vy # user_user
  password: dXNlcl9wYXNz # user_pass
  database-url: cG9zdGdyZXM6Ly91c2VyX3VzZXI6dXNlcl9wYXNzQHVzZXItcG9zdGdyZXM6NTQzMi91c2VyX2Ri
